name: Build pyglet

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:

    # Build on Linux, Windows and MacOS
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: caffeinepills/pyglet
          ref: pygodide

      - uses: astral-sh/setup-uv@v3
        # with:
          # enable-cache: true
      - run: |
          uv python install
          uv sync
          uv pip install flit


      - name: build_pyglet
        run: |
          git add . # what ever changed, likely uv.lock
          uv run python ./make.py dist
      
      # upload as build artefact
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: experimental
          files: |
            dist/*.whl
