name: Update pyglet wheel

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:

    # Build on Linux, Windows and MacOS
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          path: playground
      - uses: actions/checkout@v4
        with:
          repository: caffeinepills/pyglet
          ref: pygodide
          path: pyglet

      - uses: astral-sh/setup-uv@v3
        # with:
          # enable-cache: true
      - run: |
          uv python install
          cd $GITHUB_WORKSPACE/pyglet
          uv sync
          uv pip install flit


      - name: build_pyglet
        run: |
          pwd
          git status
          uv run python ./make.py dist
      
      - name: update vendored wheel
        run: |
          git add . # what ever changed, likely uv.lock
          uv run python ./make.py dist


      - name: update vendored wheel
        run: |
          cd $GITHUB_WORKSPACE
          cp -f pyglet/dist/*.whl playground/wheels/
          cd playground
          git add *.whl
          git commit -m "update pyglet wheel"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: playground
          
